FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceph_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='ceph') }}

{% if base_package_type == 'rpm' %}

   {% set ceph_base_packages = [
        'btrfs-progs',
        'ceph',
        'ceph-mgr-dashboard',
        'ceph-radosgw',
        'e2fsprogs',
        'gdisk',
        'hdparm',
        'parted',
        'smartmontools',
        'xfsprogs'
    ] %}

    {% if base_arch in ['aarch64', 'x86_64'] %}
        {% set ceph_base_packages = ceph_base_packages + [
            'ceph-fuse'
        ] %}
    {% endif %}

{% endif %}
{{ macros.install_packages(ceph_base_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ceph_base_footer %}{% endblock %}
